// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace SbsApiV2.Models
{

    public class Account
    {

        [JsonProperty("AccountTransactionSearchUri")]
        public object AccountTransactionSearchUri { get; set; }

        [JsonProperty("UpcomingPayments")]
        public object UpcomingPayments { get; set; }

        [JsonProperty("AccountTransactionListResponseDocument")]
        public object AccountTransactionListResponseDocument { get; set; }

        [JsonProperty("AccountUri")]
        public string AccountUri { get; set; }

        [JsonProperty("AdditionalText")]
        public object AdditionalText { get; set; }

        [JsonProperty("Balance")]
        public string Balance { get; set; }

        [JsonProperty("AvailableFunds")]
        public string AvailableFunds { get; set; }

        [JsonProperty("Icon")]
        public int Icon { get; set; }

        [JsonProperty("Id")]
        public int Id { get; set; }

        [JsonProperty("AllowsDeposit")]
        public bool AllowsDeposit { get; set; }

        [JsonProperty("AllowsWithdrawal")]
        public bool AllowsWithdrawal { get; set; }

        [JsonProperty("FullAuthority")]
        public bool FullAuthority { get; set; }

        [JsonProperty("publicAuthorityOnly")]
        public bool publicAuthorityOnly { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Number")]
        public string Number { get; set; }

        [JsonProperty("CustomerNumber")]
        public string CustomerNumber { get; set; }

        [JsonProperty("AccountPartnersUri")]
        public string AccountPartnersUri { get; set; }

        [JsonProperty("IsInvestmentAccount")]
        public bool IsInvestmentAccount { get; set; }

        [JsonProperty("PaperStatementsSupressed")]
        public bool PaperStatementsSupressed { get; set; }

        [JsonProperty("ChequeBookEnabled")]
        public bool ChequeBookEnabled { get; set; }

        [JsonProperty("DepositBookEnabled")]
        public bool DepositBookEnabled { get; set; }

        [JsonProperty("AvailableForSmsAlerts")]
        public bool AvailableForSmsAlerts { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }
    }

    public class ProfileAccount
    {

        [JsonProperty("Accounts")]
        public Account[] Accounts { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }
    }

    public class Address
    {

        [JsonProperty("Code")]
        public string Code { get; set; }

        [JsonProperty("AddressLines")]
        public string AddressLines { get; set; }

        [JsonProperty("PostCode")]
        public string PostCode { get; set; }
    }

    public class ProfileEmailAddress
    {

        [JsonProperty("Code")]
        public string Code { get; set; }

        [JsonProperty("EmailAddress")]
        public string EmailAddress { get; set; }

        [JsonProperty("Default")]
        public bool Default { get; set; }
    }

    public class PhoneNumber
    {

        [JsonProperty("Code")]
        public string Code { get; set; }

        [JsonProperty("Number")]
        public string Number { get; set; }

        [JsonProperty("Area")]
        public string Area { get; set; }

        [JsonProperty("Country")]
        public string Country { get; set; }

        [JsonProperty("Extension")]
        public string Extension { get; set; }

        [JsonProperty("Default")]
        public bool Default { get; set; }
    }

    public class AccountAlert
    {

        [JsonProperty("AlertActive")]
        public bool AlertActive { get; set; }

        [JsonProperty("AlertId")]
        public int AlertId { get; set; }

        [JsonProperty("AlertDefinitionId")]
        public int AlertDefinitionId { get; set; }

        [JsonProperty("Amount")]
        public string Amount { get; set; }

        [JsonProperty("AccountId")]
        public int AccountId { get; set; }

        [JsonProperty("Frequency")]
        public string Frequency { get; set; }

        [JsonProperty("FrequencyNextDate")]
        public object FrequencyNextDate { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }
    }

    public class AccountByAlert
    {

        [JsonProperty("AccountId")]
        public int AccountId { get; set; }

        [JsonProperty("AccountAlerts")]
        public AccountAlert[] AccountAlerts { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }
    }

    public class AlertDefinition
    {

        [JsonProperty("AlertDefinitionId")]
        public int AlertDefinitionId { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("AlertType")]
        public string AlertType { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }
    }

    public class AlertDefinitionsOverview
    {

        [JsonProperty("AlertDefinitions")]
        public AlertDefinition[] AlertDefinitions { get; set; }

        [JsonProperty("AlertTypes")]
        public string[] AlertTypes { get; set; }

        [JsonProperty("Frequencies")]
        public string[] Frequencies { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }
    }

    public class AccountsAlertsUpdate
    {

        [JsonProperty("FeesAccount")]
        public string FeesAccount { get; set; }

        [JsonProperty("AccountByAlerts")]
        public AccountByAlert[] AccountByAlerts { get; set; }

        [JsonProperty("AlertDefinitionsOverview")]
        public AlertDefinitionsOverview AlertDefinitionsOverview { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }
    }

    public class Customer
    {

        [JsonProperty("PreferredContactDetailSummary")]
        public string PreferredContactDetailSummary { get; set; }

        [JsonProperty("Addresses")]
        public Address[] Addresses { get; set; }

        [JsonProperty("EmailAddresses")]
        public ProfileEmailAddress[] EmailAddresses { get; set; }

        [JsonProperty("PhoneNumbers")]
        public PhoneNumber[] PhoneNumbers { get; set; }

        [JsonProperty("DefaultHomePageAccount")]
        public int DefaultHomePageAccount { get; set; }

        [JsonProperty("DefaultTransactionAccount")]
        public int DefaultTransactionAccount { get; set; }

        [JsonProperty("FirstName")]
        public string FirstName { get; set; }

        [JsonProperty("LastName")]
        public string LastName { get; set; }

        [JsonProperty("PreferredMeansOfContact")]
        public string PreferredMeansOfContact { get; set; }

        [JsonProperty("PreferredTimeOfContact")]
        public string PreferredTimeOfContact { get; set; }

        [JsonProperty("SecurityUri")]
        public string SecurityUri { get; set; }

        [JsonProperty("AccountsAlertsUpdate")]
        public AccountsAlertsUpdate AccountsAlertsUpdate { get; set; }

        [JsonProperty("CustomerUri")]
        public string CustomerUri { get; set; }

        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("PreferredName")]
        public string PreferredName { get; set; }

        [JsonProperty("Number")]
        public string Number { get; set; }

        [JsonProperty("OwnerBadge")]
        public int OwnerBadge { get; set; }

        [JsonProperty("CustomerStatus")]
        public string CustomerStatus { get; set; }

        [JsonProperty("MobileWebsiteUpdateCount")]
        public int MobileWebsiteUpdateCount { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }
    }

    public class ProfileResponse
    {

        [JsonProperty("Accounts")]
        public ProfileAccount Accounts { get; set; }

        [JsonProperty("Customer")]
        public Customer Customer { get; set; }

        [JsonProperty("DocumentType")]
        public string DocumentType { get; set; }
    }

}
